feat: upgrade ds-card-reader service to edgex 2.2
intel-iot-devkit/automated-checkout pull request #16
Opened 2022-09-01 22:33 UTC by vli11

Signed-off-by: Valina Li <valina.li@intel.com>

2022-09-01 22:44 UTC, lenny-intel requested changes

2022-09-01 22:44 UTC, lenny-intel commented on ds-card-reader/device/physical.go
> +		cardNumber,
Maybe resource name `card-data` in the device profile should be `card-number`. Would be a better descriptive name.

2022-09-01 22:44 UTC, lenny-intel commented on ds-card-reader/device/physical.go
> +		reader.Write(common.CommandCardData, reader.CardNumber)
```suggestion
		reader.Write(common.CommandCardNumber, reader.CardNumber)
```

2022-09-01 22:44 UTC, lenny-intel commented on docs_src/automated-checkout-services/device_services.md
> +curl -X PUT -H "Content-Type: application/json" -d '{"card-data":"0003278200"}' http://localhost:48098/api/v2/device/name/card-reader/card-data
```suggestion
curl -X PUT -H "Content-Type: application/json" -d '{"card-number":"0003278200"}' http://localhost:48098/api/v2/device/name/card-reader/card-number
```

2022-09-01 22:44 UTC, lenny-intel commented on ds-card-reader/common/common.go
> +	CommandCardData         = "card-data"
```suggestion
	CommandCardNumber         = "card-number"
```

2022-09-01 22:44 UTC, lenny-intel commented on ds-card-reader/device/virtual_test.go
> +	reader.Write(common.CommandCardData, expectedCardNumberVirtual)
```suggestion
	reader.Write(common.CommandCardNumber, expectedCardNumberVirtual)
```

2022-09-01 22:44 UTC, lenny-intel commented on ds-card-reader/driver/driver.go
> +	case common.CommandCardData:
```suggestion
	case common.CommandCardNumber:
```

2022-09-01 22:44 UTC, lenny-intel commented on ds-card-reader/driver/driver.go
> +			drv.CardReader.Write(common.CommandCardData, cardNumber)
```suggestion
			drv.CardReader.Write(common.CommandCardNumber, cardNumber)
```

2022-09-01 22:44 UTC, lenny-intel commented on ds-card-reader/driver/driver_test.go
> +	successfulCommandVal, err := dsModels.NewCommandValueWithOrigin(common.CommandCardData, edgexcommon.ValueTypeString, expectedCardNumber, 0)
```suggestion
	successfulCommandVal, err := dsModels.NewCommandValueWithOrigin(common.CommandCardNumber, edgexcommon.ValueTypeString, expectedCardNumber, 0)
```

2022-09-01 22:44 UTC, lenny-intel commented on ds-card-reader/driver/driver_test.go
> +	nonStringCommandVal, err := dsModels.NewCommandValueWithOrigin(common.CommandCardData, edgexcommon.ValueTypeFloat64, 0.01, 0)
```suggestion
	nonStringCommandVal, err := dsModels.NewCommandValueWithOrigin(common.CommandCardNumber, edgexcommon.ValueTypeFloat64, 0.01, 0)
```

2022-09-01 22:44 UTC, lenny-intel commented on ds-card-reader/driver/driver_test.go
> +			fmt.Errorf("write command \"%v\" received non-string value: %v", common.CommandCardData, "cannot convert CommandValue of Float64 to String"),
```suggestion
			[]string{fmt.Sprintf("write command \\\"%v\\\" received non-string value: %v", common.CommandCardNumber, "cannot convert CommandValue of Float64 to String")},
			fmt.Errorf("write command \"%v\" received non-string value: %v", common.CommandCardNumbera, "cannot convert CommandValue of Float64 to String"),
```

2022-09-01 22:44 UTC, lenny-intel commented on ds-card-reader/res/configuration.toml
> +
Where did this come from? Now the file we were working with.

2022-09-01 22:44 UTC, lenny-intel commented on ds-card-reader/res/profiles/ds-card-reader.yaml
> +  description: "Data received from card reader"
```suggestion
- name: "card-number"
  description: "Card number received from card reader"
```

2022-09-02 00:14 UTC, jim-wang-intel requested changes

2022-09-02 00:14 UTC, jim-wang-intel commented on ds-card-reader/device/physical.go
> +		fmt.Errorf("error on NewCommandValueWithOrigin for %v", commandName)
what are we trying to do with this err formatting?  should we log it here?
Also should we include err details in part of Errorf?

2022-09-02 00:14 UTC, jim-wang-intel commented on ds-card-reader/device/virtual.go
> +		fmt.Errorf("error on NewCommandValueWithOrigin for %v", commandName)
similar comment above

2022-09-02 17:22 UTC, jim-wang-intel commented on ds-card-reader/device/physical.go
> +		reader.LoggingClient.Error(fmt.Sprintf("error on NewCommandValueWithOrigin for %v", commandName))
```suggestion
		reader.LoggingClient.Errorf("error on NewCommandValueWithOrigin for %v: %v", commandName, err)
```

2022-09-02 17:22 UTC, jim-wang-intel commented on ds-card-reader/device/virtual.go
> +		reader.LoggingClient.Error(fmt.Sprintf("error on NewCommandValueWithOrigin for %v", commandName))
```suggestion
		reader.LoggingClient.Errorf("error on NewCommandValueWithOrigin for %v: %v", commandName, err)
```

2022-09-02 17:49 UTC, jim-wang-intel approved these changes
LGTM

2022-09-02 19:22 UTC, brian-intel requested changes
There is a reference to the endpoint in the phase 1 of the documentation that will also need to be updated. that  code can be found here: /docs/phases/phase1.html

2022-09-06 16:28 UTC, lenny-intel approved these changes
LGTM

2022-09-06 16:30 UTC, brian-intel approved these changes

2022-09-06 16:30 UTC, merged