feat: add more logging to ms-ledger functions
intel-iot-devkit/automated-checkout pull request #38
Opened 2022-09-20 22:09 UTC by vli11

Signed-off-by: Valina Li <valina.li@intel.com>

2022-09-20 22:13 UTC, jim-wang-intel approved these changes

2022-09-20 22:15 UTC, lenny-intel requested changes

2022-09-20 22:15 UTC, lenny-intel commented on ms-ledger/routes/deletes.go
> +			c.lc.Errorf("Failed to retrieve all ledgers for accounts %s", err.Error())
Don't repeat the message from previous line, put it in a string variable and use in both places. Same for all these log messages in all these files.

2022-09-20 22:18 UTC, joshua-silverio approved these changes

2022-09-20 22:27 UTC, brian-intel approved these changes
LGTM

2022-09-21 16:28 UTC, lenny-intel approved these changes
LGTM

2022-09-21 16:29 UTC, merged