fix: ds-controller-board unit test
intel-iot-devkit/automated-checkout pull request #60
Opened 2022-09-28 18:38 UTC by vli11

Signed-off-by: Valina Li <valina.li@intel.com>

2022-09-28 21:44 UTC, jim-wang-intel approved these changes
LGTM

2022-09-28 22:59 UTC, lenny-intel requested changes

2022-09-28 22:59 UTC, lenny-intel commented on ds-controller-board/device/virtual_test.go
> +	dsModels "github.com/edgexfoundry/device-sdk-go/v2/pkg/models"
This is the same package as above, just aliased. Remove this one and use the non-aliased one.

2022-09-28 22:59 UTC, lenny-intel commented on ds-controller-board/driver/driver_test.go
> +			}
Too much going on in one line for readablity. Please break it up like we did for your test in other PR and use require.Error/require.NoError

2022-09-28 22:59 UTC, lenny-intel commented on ds-controller-board/driver/driver_test.go
> +				require.Nil(actual)
add `return` here to avoid else

2022-09-28 23:20 UTC, lenny-intel approved these changes
LGTM

2022-09-29 17:37 UTC, joshua-silverio approved these changes
LGTM

2022-09-29 17:50 UTC, brian-intel approved these changes

2022-09-29 17:50 UTC, brian-intel commented on ds-controller-board/driver/driver.go
> +			return fmt.Errorf("unknown Command Type: '%v'", cmdType)
Good change. We don't know what this type will be so allowing go to do the casting is much better

2022-09-29 18:28 UTC, marcpfuller approved these changes
LGTM

2022-09-29 19:01 UTC, merged